language: ruby
rvm:
  - 2.4
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _site
  repo: western-bioinfo.github.io
  target_branch: master
  fqdn: western-bioinfo.github.io
notifications:
  email:
    recipients:
      - apoon42@uwo.ca
    on_success: always
    on_failure: always
